hdfs:
        server: http://hdfs_hostname:50070
        canonicalize_hostname: False
        hdfs_user: "test"
        hdfs_group: "foobarbaz"
        mount_root: "/users/test"
        kerberos: True
mount:
        dest_dir: /tmp/myhdfsmount
        extra:
                allow_root: False
                allow_other: False
                nothreads: False
